// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIsPp1bKVw33CevWV_79q35xCtcY8kGws',
    appId: '1:749876274717:web:1e98b988bf9e99881d88f4',
    messagingSenderId: '749876274717',
    projectId: 'b2vtechnew',
    authDomain: 'b2vtechnew.firebaseapp.com',
    storageBucket: 'b2vtechnew.firebasestorage.app',
    measurementId: 'G-6FPTWW0W0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb8Ls3_9wrcreWlGIf6ngMwY_sRrrLp7U',
    appId: '1:749876274717:android:5d9a7a08c6575e391d88f4',
    messagingSenderId: '749876274717',
    projectId: 'b2vtechnew',
    storageBucket: 'b2vtechnew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjRI0JlvOvxVH060eCSO4O859YY-IUczg',
    appId: '1:749876274717:ios:2889ed262e0bd64c1d88f4',
    messagingSenderId: '749876274717',
    projectId: 'b2vtechnew',
    storageBucket: 'b2vtechnew.firebasestorage.app',
    iosBundleId: 'com.example.b2vAdminPanel',
  );
}
